name: Build Pascal

on:
  push:
    branches: [ main ]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Free Pascal
        run: |
          sudo apt update
          sudo apt install -y fpc fp-units-net

      - name: Build
        run: |
          fpc -Mobjfpc -Sh pspkg.pas
